---
title: "R Notebook"
output: html_notebook
---

```{r}
print("Tahap 1")
```
```{r}
0x <- c(7,6,8,5,9,9.5,8.3,7.5)
y <- c(1.2,1.7,1.5,1.3,1.0,1.4,0.8,1.1)
merk <- c('A','B','C','D','E','F','G','H')

plot(x,y, col = "blue",main = "Data Produk", cex = 1.3, pch = 16, xlab = 'keasaman', ylab = "keleturan")
text(x,y, label=merk, cex = 0.7, pos=3)
```
```{r}
data = matrix(c(7,1.2, 6,1.7, 8,1.5, 5,1.3, 9,1.0, 9.5,1.4, 8.3,0.8, 7.5, 1.1),8,2,TRUE)
print(data)
```
```{r}
# dataframe
df = data.frame(id = c("A", "B", "C", "D", "E", "F", "G", "H"), jarak1 = c(7, 6, 8, 5, 9, 9.5, 8.3, 7.5), jarak2 = c(1.2, 1.7, 1.5, 1.3, 1.0, 1.4, 0.8, 1.1))
print(df)
```
```{r}
# Test rumus
hasil = sqrt((7.5-7)^2+(1.1-1.2)^2)
print(hasil)
print(nrow(df))
a = 1
print(df[8,2])
```
```{r}
print("Menghitung jarak dengan Euclidean distance \n")
toris = nrow(df)
a=1
nilai_d = c()
d = c()
while(a<toris){
  hasil = sqrt((df[toris,2] - df[a,2])^2 + (df[toris,3]-df[a,3])^2)
  nilai_d = c(nilai_d, hasil)
  d = c(d,paste("H",df[a,1], sep =""))
  print(paste("Hasil dari d H",df[a,1]," : ",hasil,sep=""))
  a=1+a
}
```
```{r}
data_hasil = data.frame( d = d,nilai_d=nilai_d )
print(data_hasil)
```
```{r}
urut = data_hasil[order(data_hasil$nilai_d),]
print(urut)
```
```{r}
nilai_bagus_x <- c(7.0,8.0,8.3)
nilai_bagus_y <- c(1.2,1.5,0.8)
plot(x,y, col = "blue",main = "Data Produk", cex = 1.3, pch = 16, xlab = 'keasaman', ylab = "keleturan")
text(x,y, label=merk, cex = 0.7, pos=3)
points(nilai_bagus_x,nilai_bagus_y,col ="red",pch=4, lwd=2, cex=2)
points(7.5, 1.1,col="black",pch = 22, lwd=2, cex=2)
```

```{r}
# membuat array produk
x <- c(7,6,8,5,9,9.5,8.3,7.5)
y <- c(1.2,1.7,1.5,1.3,1.0,1.4,0.8,1.1)

bagus_x <- c(7,8,9,9.5)
bagus_y <- c(1.2,1.5,1.0,1.4)

kurang_x <- c(6,5,8.3)
kurang_y <- c(1.7,1.3,0.8)

test_x <- c(7.5)
test_y <- c(1.1)
```

```{r}
# Membuat array merk
merk_bagus <- c('A','c','E','f')
merk_kurang <- c('B','D','G')
merk_test <- c('H')
```

```{r}
plot(x,y,col="blue", main = "Data produk", cex = 1.3, pch = 16, xlab = "keasama", ylab = "kelenturan")
points(bagus_x,bagus_y,col ="red",pch=4, lwd=2, cex=2)
points(test_x, test_y,col="black",pch = 22, lwd=2, cex=2)
```
```{r}
```
```{r}
kurang_x <- c(6,5,8.3)
kurang_y <- c(1.7,1.3,0.8)
```

```{r}
# Memplot merk
#plot(bagus_x, bagus_y, col = "red", pch = 4, lwd = 2, cex = 2)
#text(bagus_x,bagus_y,labels = merk_bagus, cex = 0.7, pos = 3)
#text(kurang_x,kurang_y,labels = merk_kurang, cex = 0.7, pos = 3)
#text(test_x, test_x, labels = merk_test, cex = 0.7, pos = 3)
#legend("bottomleft",legend = c("","",""), title = "", col = "black",pch = c(19,19,19), bty = "n",pt.cex = 1,cex = 1.2, text.col = "black", horiz = F, inset = c(0.1,0.1))
#legend("bottomleft",legend = c("Bagus","Kurang Bagus","Data uji"),title = "Keterangan :",col = "black", pch = #c(4,20,22),bty = "n", pt.cex = 1.7, cex = 1.2, text.col = "black",horiz = F, inset = c(0.1,0.1))
```
```{r}
plot(x,y,col="blue", main = "Data produk", cex = 1.3, pch = 16, xlab = "keasama", ylab = "kelenturan")
points(bagus_x,bagus_y,col ="red",pch=4, lwd=2, cex=2)
points(test_x, test_y,col="black",pch = 22, lwd=2, cex=2)
# Memplot merk
text(bagus_x,bagus_y,labels = merk_bagus, cex = 0.7, pos = 3)
text(kurang_x,kurang_y,labels = merk_kurang, cex = 0.7, pos = 3)
text(test_x, test_x, labels = merk_test, cex = 0.7, pos = 3)
legend("bottomleft",legend = c("","",""), title = "", col = "black",pch = c(19,19,19), bty = "n",pt.cex = 1,cex = 1.2, text.col = "black", horiz = F, inset = c(0.1,0.1))
legend("bottomleft",legend = c("Bagus","Kurang Bagus","Data uji"),title = "Keterangan :",col = "black", pch = c(4,20,22),bty = "n", pt.cex = 1.7, cex = 1.2, text.col = "black",horiz = F, inset = c(0.1,0.1))
```
```{r}
p1 <- plot(function(x){x^(2)/2}
    ,0,100
    ,xlab = "x"
    ,ylab = "y"
    ,ylim = c(0,5000)
    ,las = 1
    ,type = "p"
    ,cex = 0.8
    ,pch = 21
    ,col = "red"
)
par(new=TRUE)
p2 <- plot(function(x){(1-x^(2))/2}
  ,0,100
  ,xlab = ""
  ,ylab = ""
  ,axes = FALSE
  ,type = "p"
  ,cex = 0.8
  ,pch = 22
  ,col = "blue"
)
par(new=TRUE)
l <- legend("topleft"
  ,inset = c(0,0.4)
  ,cex = 1.5
  ,bty = "n"
  ,legend = c("Bagus","Kurang bagus")
  ,text.col = c("red","blue")
  ,pt.bg = c("red","blue")
  ,pch = c(21,22)
)
```
```{r}
curve(x^(2)/2,from = 0,to = 100,col = 'red',type = 'p',pch = 16, n =20)
curve((1-x^(2))/2 + 5000, from = 0, to = 100,col = 'blue', type = 'p',pch = 15, add = TRUE, n = 20)
legend("topleft",
       inset = c(0,0.4),
       cex = 1.5,
       bty = "n",
       legend = c("A","B"),
       text.col = c("red","blue"),
       col = c("red","blue"),
       pch = c(16,15)
       )
```
```{r}
x <- mtcars[order(mtcars$mpg),] # sort by mpg
x$cyl <- factor(x$cyl) # it must be afactor
x$color[x$cyl==4] <- "red"
x$color[x$cyl==6] <- "blue"
x$color[x$cyl==8] <- "darkgreen"
dotchart(x$mpg, labels= row.names(x), cex = .7,groups = x$cyl, main = "Gas Milage for Car Models\ngrouped by cylinder", xlab = "Miles per Gallon", gcolor = "black", color = x$color)
```
```{r}
A <- c(7,1.2)
B <- c(6,1.7)
C <- c(8,1.5)
D <- c(5,1.3)
E <- c(9,1.0)
F <- c(9.5,1.4)
G <- c(8.3,0.8)
H <- c(7.5,1.1)

dha <- sqrt(sum((H-A)^2))
dhb <- sqrt(sum((H-B)^2))
dhc <- sqrt(sum((H-C)^2))
dhd <- sqrt(sum((H-D)^2))
dhe <- sqrt(sum((H-E)^2))
dhf <- sqrt(sum((H-F)^2))
dhg <- sqrt(sum((H-G)^2))

d<- c(dha,dhb,dhc,dhd,dhe,dhf,dhg)
d

```

```{r}
sort(d)
```
```{r}
d
```

```{r}
# Listing program 4.3 Bubblesort
bubblesort <- function(x){
  for (last in length(x):2) {
    for(first in 1:(last - 1)){
      if(x[first] > x[first+1]){ # swap the pair
        save <- x[first]
        x[first] <- x[first + 1]
        x[first + 1] <- save
      }
    }
  }
  return (x)
}
```

```{r}
bubblesort(d)
```
```{r}
# listing program 4.4 Modifikasi Bubblesort
sortknn <- function(d,k){
  for (last in length(d):2) {
    for (first in 1:(last - 1)){
      if(d[first] > d[first + 1]){
        save <- d[first]
        d[first] <- d[first + 1]
        d[first + 1] <- save
      }
    }
  }
  return (d[1:k])
}
```





























