---
title: "Latihan kNN ke 2"
output: html_notebook
---


```{r}
data = matrix(c(  "A",7,1.2,"Bagus"
                , "B",6,1.7,"Kurang bagus"
                , "C",8,1.5,"Bagus"
                , "D",5,1.3,"Kurang bagus"
                , "E",9,1.0,"Bagus"
                , "F",9.5,1.4,"Bagus"
                , "G",8.3,0.8,"Kurang bagus"
                , "H",7.5,1.1,"?"
                ),8,4,TRUE)
print(data)
```
```{r}
data_kebalik = t(data)
print(data_kebalik)
```
```{r}
# dataframe
df = data.frame(x = c(7, 6, 8, 5, 9, 9.5, 8.3, 7.5), y = c(1.2, 1.7, 1.5, 1.3, 1.0, 1.4, 0.8, 1.1), KAT = c("Bagus", "Kurang bagus", "Bagus", "Kurang bagus", "Bagus", "Bagus", "Kurang bagus", "?"))
df_kebalik = t(df)
print(df_kebalik)

```
```{r}
KAT_df<-df[3]
print(KAT_df)
```
```{r}
cari_df<-df[df[,"KAT"]=="Kurang bagus",]
print(cari_df)
```
```{r}
# Terdapat 8 perintah dasar yang akan sangat digunakan dalam kegiatan manipulasi data. Semua fungsi-fungsi dibawah ini sudah termasuk di dalam paket dplyr.

# filter(): Mengambil baris berdasarkan kondisi nilainya.
# distinct(): Menghilangkan baris yang sama atau duplikat.
# arrange(): Mengurutkan baris.
# select(): Mengambil kolom berdasarkan nama kolomnya.
# rename(): Mengubah nama kolom.
# mutate(): Menambahkan atau membuat kolom baru dan menjaga kolom sama yang sudah ada.
# transmute(): Menambahkan atau membuat kolom baru dan menghapus kolom yang sama atau sudah ada
# summarise(): Melakukan komputasi statistika (Contoh: menghitung total (sum) atau rata-rata (mean))

# Adapun fungsi-fungsi yang akan digunakan seperti:

# pull(): Mengambil hanya data atau isi dari kolom berupa vector.
# select(): Memanggil satu atau lebih kolom berupda data table.
# select_if(): Memanggil kolom dengan pengkondisian.
# Helper functions - starts_with(), ends_with(), contains(), matches(), one_of(): Memanggil kolom berdasarkan kriteria tertentu atas nama kolomnya.
```

```{r}
# menghilangkan "kurang bagus" menjadi "kurang"
df$KAT[df$KAT == "Kurang bagus"] <- "Kurang"
df
```
```{r}
train <- df[1:2]
train
```
```{r}
test <- df[8,]
test <- test[1:2]
test
```
```{r}
train <- train[-8,]
train
```
```{r}
cl <- df[3]
cl <- cl[-8,]
cl
```
```{r}
library(class)
hasil <- knn(train, test, cl, k=3)
hasil
```
```{r}
hasil_knn <- cbind(test, label=as.vector(hasil))
```
```{r}
hasil_knn
```
```{r}
hasil <- knn(train, test, cl, k=3, prob=T)
hasil
```
```{r}
iris
head(iris)
```
```{r}
class(iris)
```
```{r}
str(iris)
```
```{r}
colnames(iris)
```
```{r}
iris[,"Petal.Length"]
```
```{r}
# informasi detail utk dataset iris dpt ditampilkan
summary(iris)
```
```{r}
plot(iris$Petal.Length, iris$Petal.Width, main = "Edgar Anderson`s Iris Data")
```
```{r}
plot(iris$Petal.Length, 
     iris$Petal.Width, 
     pch=21,
     bg = c("red","green3","blue"),
     main = "Edgar Anderson`s Iris Data")
```
```{r}
plot(iris$Petal.Length, 
     iris$Petal.Width, 
     pch=c(23,24,25)[unclass(iris$Species)],
     main = "Edgar Anderson`s Iris Data")
```
```{r}
plot(iris)
```
```{r}
library(class)
data(iris)
```

```{r}
# Tahap 1
# Random sampling
set.seed(99)
rannum <- sample(rep(1:150))
rannum
```
```{r}
iris <- iris[rannum,]
iris
```
```{r}
# Tahap 2
# Normalisasi dataset

normalisasi <- function(data){
  return((data - min(data))(max(data)-min(data)))
}

# Proses normalisasi data adalah hal yg umum dilakukan dlm berbagai kegiatan riset. Proses normalisasi tidak akan mengubah "arti" dari data yang ada.

```

```{r}
# selanjutnya buat objek baru utk menampung hasil normalisasi.kita memerlukan fungsi lapply

# iris.normal <- as.data.frame(lapply(iris[,c(1,2,3,4)],normalisasi))
iris.normal <- as.data.frame(lapply(iris[,c(1,2,3,4)],scale))
head(iris.normal)
```
```{r}
# bandingkan dengan sebelumnya
head(iris)
```
```{r}
# Tahap 3
# Memisahan antara data training dan data uji.

# tentukan 80% dari dataset, yaitu 120 buah data, utk data training.
iris.train <- iris.normal[1:120,]

# Tentukan klaisifikasi utk data training
iris.train.target <- iris[1:120,5]

# tentukan 20% dari dataset, yaitu 30 buah data, utk data uji
iris.test <- iris.normal[121:150,]
iris.test.target <- iris[121:150,5]

summary(iris.normal)
```
```{r}
# Tahap 4
# Menjalankan algoritma k-NN dgn bantuan fungsi knn().

knnhasil <- knn(train = iris.train, test = iris.test, cl = iris.train.target, k=19)
knnhasil
```
```{r}
hasil_knn <- cbind(iris.test, label = as.vector(knnhasil))
hasil_knn
```
```{r}
# Tahap 5
# Memverikasi hasil.

# perintah utk pembentukan confusion matrix sebagai berikut:
table(iris.test.target,knnhasil)
```
```{r}
# kita bisa menabahkan opsi prob = T utk melihat probabilitas utk nilai k sesuai pilihan kita.

knnhasil <- knn(train = iris.train, test = iris.test, cl = iris.train.target, k=19, prob = T)
knnhasil
```
```{r}
library(class)
library(ggplot2)
# visuasisasi hasil knn

dataplot <- ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Species))
dataplot + geom_point(size = 0.5) + geom_smooth()


```































